In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [108]:
a=0.5
A=np.array([[1,2],[3,6+a]])
x=np.array([1,1])
y=A@x

In [109]:
U, s, Vh = np.linalg.svd(A) 

In [110]:
U

array([[-0.2980334 , -0.95455544],
       [-0.95455544,  0.2980334 ]])

In [111]:
s

array([7.49970367, 0.0666693 ])

In [112]:
Vh

array([[-0.42157662, -0.90679278],
       [-0.90679278,  0.42157662]])

In [126]:
xr=(U.T@y@Vh.T)/s[0]
xr

array([0.56392082, 1.20273737])

In [122]:
A@xr

array([2.96939557, 9.50955538])

In [115]:
y

array([3. , 9.5])

In [116]:
np.linalg.solve(A,y)

array([1., 1.])